### ISSUE TITLE
Cannot install DiffRules

### ISSUE THREAD

**Issue by SamZhou1996** [JuliaDiff/DiffRules.jl#3]
Cannot use `Pkg.add("DiffRules")` to install the package, Julia returns `ERROR: unknown package DiffRules`.

**Comment by jrevels** [comment]
Did you try running `Pkg.update()` to make sure METADATA is updated? DiffRules is registered in METADATA, so `Pkg.add` should work if you're using Julia v0.6

**Comment by SamZhou1996** [comment]
It works now! Thanks!
