### ISSUE TITLE
Release a major?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiff/DiffRules.jl#43]
Updating SpecialFunctions requires another big bump... this gets annoying. @jrevels @oxinabox how about just making a 1.0 here for this? I don't think it'll change all that much.

**Comment by oxinabox** [comment]
once https://github.com/JuliaDiff/ChainRules.jl/issues/134
is done we can look at deprecating DiffRules

**Comment by ChrisRackauckas** [comment]
I still think we should make this get an update for SpecialFunctions compatibility anyways.

**Comment by oxinabox** [comment]
Yeah, it definately needs a new release tagged. Wether that is 1.0 or 0.2. 🤷‍♂

**Comment by ChrisRackauckas** [comment]
I'm just going for it. It'll make everyone happy in the long run.

@JuliaRegistrator register()
