### ISSUE TITLE
Lack rule for `ifelse`

### ISSUE THREAD

**Issue by wupeifan** [JuliaDiff/DiffRules.jl#47]
I was wondering whether a rule for `ifelse(condition, exp1, exp2)` can be created? Thanks a lot!

**Comment by JianghuiDu** [comment]
Most of the times `ifelse` can be replaced by combinations of `max` and `mix` which are included in `DiffRules.jl`. 
Something like this https://exceljet.net/replace-ugly-ifs-with-max-or-min.

**Comment by wupeifan** [comment]
I raised this issue exactly because I want to avoid max and min combinations, but thanks for your suggestions.

**Comment by mcabbott** [comment]
Should be simple to add, and worth having IMO.

**Comment by wupeifan** [comment]
I think it should be something like `D(ifelse(condition, exp1, exp2)) = ifelse(condition, D(exp1), D(exp2))`. If it is just this simple then I can make a little PR, but I don't know whether there are other potential issues.

**Comment by mcabbott** [comment]
I was thinking it looks like this, but I'm not sure that `false` is actually the right thing... in Zygote etc. it would be `nothing`: 
```
@define_diffrule Base.:ifelse(p, x, y) = :(false), :($p), :(!$p)
```
